### ISSUE TITLE
Parsing: hgld: entries contain multiple lexemes, separated by `,`

### ISSUE THREAD

**Issue by chrzyki** [lexibank/huntergatherer#1]
_From @xrotwang on July 15, 2016 19:37_

These entries should be split. Also, often a specific meaning is indicated enclosed in `"`, e.g.

```
kohI, kohhi7 “small intestine, waist, abdomen”
```

For some languages, `[]` seem to be used, e.g.:

```
ĩík [swell], pux [pot boil over]
```

_Copied from original issue: glottobank/lexibank-data#2_

**Comment by SimonGreenhill** [comment]
formspec should handle this.
